### ISSUE TITLE
Unauthorized request to Lambda ListFunctions gives "Unhandled Error" instead of ClientError.accessDenied

### ISSUE THREAD

**Issue by helje5** [soto-project/soto#380] opened 2020-09-19 12:29 UTC
When calling Lambda ListFunctions on a user which doesn't have permissions to do so, soto returns an "unhandled" `SotoCore.AWSError` (w/ status 403).

I think this should rather return an AWSClientError.accessDenied?

log:
```
Request:
  ListFunctions
  GET https://lambda.eu-west-3.amazonaws.com/2015-03-31/functions/?MaxItems=1000
  Headers: [
    user-agent : Soto/5.0
  ]
  Body: empty
Response:
  Status : 403
  Headers: [
    x-amzn-requestid : a4745665-1725-4fa8-a60c-ab69d35c4923
    date : Sat, 19 Sep 2020 12:24:39 GMT
    content-type : application/json
    x-amzn-errortype : AccessDeniedException
    content-length : 120
  ]
  Body: 
  {"Message":"User: arn:aws:iam::xx:user/Joe is not authorized to perform: lambda:ListFunctions on resource: *"}
```

Error object:
```
▿ Unhandled Error, code: 403, body: {"Message":"User: arn:aws:iam::xx:user/Joe is not authorized to perform: lambda:ListFunctions on resource: *"}
  - message : "Unhandled Error"
  ▿ rawBody : Optional<String>
    - some : "{\"Message\":\"User: arn:aws:iam::xx:user/Joe is not authorized to perform: lambda:ListFunctions on resource: *\"}"
  - statusCode : NIOHTTP1.HTTPResponseStatus.forbidden
```

**Comment by adam-fowler** [comment] 2020-09-19 16:06
That's caused by Lambda error messages having inconsistent capitalization in the json for their errors. Code is expecting
```
{"message":"User: arn:aws:iam::xx:user/Joe is not authorized to perform: lambda:ListFunctions on resource: *"}
```

**Comment by adam-fowler** [comment] 2020-09-19 16:08
Keep doing this, you are finding all sorts of issues no one else has. Obviously the Lambda service hasn't had a real test.

**Comment by helje5** [comment] 2020-09-19 21:27
I wonder whether you could also somehow generate a test suite?

**Comment by adam-fowler** [comment] 2020-09-20 06:24
I've been using localstack for testing locally. But sometimes it isn't totally accurate with what it returns. Also it only supports a limited number of services. For testing against actual AWS services I have been extending the tests over time but testing over 200 libraries requires a load of code. I believe you have been relatively unlucky. I haven't seen this number of issues with individual services come through in a long time. 

Auto generation of test suite would be using the same assumptions that are used to generate the service code, so not sure that is helpful.

**Comment by adam-fowler** [comment] 2020-09-21 07:49
Fixed in https://github.com/soto-project/soto-core/pull/370

**Closed by adam-fowler** 2020-09-21 07:49 UTC
