### ISSUE TITLE
7.x Multipart upload not working - XML is wrong

### ISSUE THREAD

**Issue by Samsv77** [soto-project/soto#735] opened 2024-09-26 16:11 UTC
**Describe the bug**
Multipart upload is not working in 7.x, and fails with an XML error

After investigation, SOTO is sending the following XML content during Complete Multipart upload request
`<?xml version="1.0" encoding="UTF-8"?><MultipartUpload xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Part><ETag>"..."</ETag><PartNumber>1</PartNumber></Part></MultipartUpload>`

This is wrong, the correct XML tag is `CompleteMultipartUpload` instead of `MultipartUpload`

Workaround:
Implement a middleware to catch the XML and correct it

```
struct FixMultipartXMLMiddleware: AWSMiddlewareProtocol {
    func handle(
        _ request: SotoCore.AWSHTTPRequest, context: SotoCore.AWSMiddlewareContext,
        next: (SotoCore.AWSHTTPRequest, SotoCore.AWSMiddlewareContext) async throws -> SotoCore.AWSHTTPResponse
    ) async throws -> SotoCore.AWSHTTPResponse {
        var copy = request
        
        // Fix Soto 7 multipart upload XML request
        var content = String(buffer: try await copy.body.collect(upTo: .max))
        if content.starts(with: "<?xml") {
            content.replace("MultipartUpload", with: "CompleteMultipartUpload")
            copy.body = .init(string: content)
        }

        return try await next(copy, context)
    }
} 
```

**Comment by adam-fowler** [comment] 2024-09-27 05:25
So I had a quick look at this and yes you are correct the top level tag should be `CompleteMultipartUpload`. And I've found out where the issue is. The code generator is ignoring the XmlName trait in the service model in this one particular case. 

Having said that though, all my tests show multipart upload still working correctly ie the tag is ignored by AWS S3. Are you using an S3 like provider or actual AWS. 

I will fix this, but am away on holidav just now.

**Comment by Samsv77** [comment] 2024-09-27 16:03
Yes I am using a private S3 provider.
Thanks for having a look

Enjoy your holiday!

**Comment by adam-fowler** [comment] 2024-10-16 16:58
I have a fix for this. It's tangled up with a bunch of other changes which need merged as well.

**Closed** 2024-10-18 06:38 UTC
